---
- name: Download file
  win_get_url:
    url: "file://{{ cache_location }}\\{{ file }}"
    dest: "{{ download_location }}\\{{ file }}"
    force: no

- name: vcforpython27 | Install
  win_msi:
    path: "{{ download_location }}\\{{ file }}"
    state: present

- name: vcforpython27 | Delete local file
  win_file:
    path: "{{ download_location }}\\{{ file }}"
    state: absent

